server:
  port: 8888

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false
  liquibase:
    enabled: false

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/

keycloak:
  custom:
    admin-user:
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:test12345}
      create-admin-user-enabled: true
    server:
      keycloak-path: /keycloak
    migration:
      import-location: classpath:keycloak-realm-config.json