server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false