server:
  port: 0

spring:
  application:
    name: auth-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
  client:
    service-url:
      default-zone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}