version: "2.1"

services:
  database:
    container_name: auth-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1