server:
  port: 0

spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: dogGO.kontakt@gmail.com
    password: ${MAIL_PASSWORD:somePasswordToChange}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8888}/keycloak/realms/master
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8888}/keycloak/realms/master/protocol/openid-connect/certs
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/