server:
  port: 0

spring:
  application:
    name: mail-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: dogGO.kontakt@gmail.com
    password: ${MAIL_PASSWORD:somePasswordToChange}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/