server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dogGO.kontakt@gmail.com
    password: somePasswordToChange
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true