server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: gateway-service
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/api/mail/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/