server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/api/mail/**
          filters:
            - StripPrefix=2
        - id: dog-lover-service
          uri: lb://dog-lover-service
          predicates:
            - Path=/api/dog-lover/**
          filters:
            - StripPrefix=2
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    supported-submit-methods: []