server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: ${EUREKA_USER:user}
      password: ${EUREKA_PASSWORD:password}

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false